version: '3'
services:

  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=crud
      - POSTGRES_USER=mh
      - POSTGRES_PASSWORD=1q2w3e4r
    ports:
      - 5432:5432